# Generated by Django 4.0.4 on 2022-06-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_imagen_alter_avatar_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.AlterModelOptions(
            name='avatar',
            options={'verbose_name': 'Avatar', 'verbose_name_plural': 'Avatars'},
        ),
        migrations.RenameField(
            model_name='avatar',
            old_name='avatar',
            new_name='imagen',
        ),
        migrations.AlterField(
            model_name='autores',
            name='imagen',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='posts',
            name='imagen',
            field=models.URLField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
